stages:
  - nuget-restore
  - db-update
  - publish

nuget-restore_test:
  stage: nuget-restore
  script:
    - echo "Restoring NuGet Packages..."
    - nuget restore "PW.Ncels.sln"
  only:
    - test
  tags:
    - test

nuget-restore_war:
  stage: nuget-restore
  script:
    - echo "Restoring NuGet Packages..."
    - C:\ncels\nuget.exe restore "PW.Ncels.sln"
  only:
    - master
  tags:
    - war

db-update_test:
  stage: db-update
  script:
    - echo "Start backup Database..."
    - sqlcmd -S (local) -i SQLScripts\ManualScripts\BackupDB.sql  -d ncels
    - echo "Start update Database..."
    - C:\DbUpdater\DbUpdater.exe -d SQLScripts\
  variables:
    GIT_STRATEGY: none
  only:
    - test
  tags:
    - test

db-update_war:
  stage: db-update
  script:
    - echo "Start backup Database... bob217 disable this!"
   # - sqlcmd -S PORTAL -i SQLScripts\ManualScripts\BackupDB.sql -d ncels
    - echo "Start update Database..."
    - C:\ncels\DbUpdater\DbUpdater.exe -d SQLScripts\
  variables:
    GIT_STRATEGY: none
  only:
    - master
  tags:
    - war

publish_test:
  stage: publish
  script:
    - echo "Start publish Internal..."
    - msbuild PW.Prism\PW.Prism.csproj /p:DeployOnBuild=true /p:PublishProfile=Test
    - ''
    - echo "Start publish External..."
    - msbuild PW.Ncels\PW.Ncels.csproj /p:DeployOnBuild=true /p:PublishProfile=Test
    - ''
  variables:
    GIT_STRATEGY: none
  only:
    - test
  tags:
    - test

publish_war:
  stage: publish
  script:
    - echo "Start publish Internal..."
    - msbuild PW.Prism\PW.Prism.csproj /p:DeployOnBuild=true /p:PublishProfile=War
    - ''
    - echo "Start publish External..."
    - msbuild PW.Ncels\PW.Ncels.csproj /p:DeployOnBuild=true /p:PublishProfile=War
    - ''
  variables:
    GIT_STRATEGY: none
  only:
    - master
  tags:
    - war