//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.ServiceWithEdo {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:utilit.service.esedo")]
    public partial class EsedoException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:common.service.edo")]
    public partial class Attachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string contentField;
        
        private string signField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string sign {
            get {
                return this.signField;
            }
            set {
                this.signField = value;
                this.RaisePropertyChanged("sign");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:in.service.edo")]
    public partial class InParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_letter_obkField;
        
        private string id_edoField;
        
        private string date_letterField;
        
        private string user_obkField;
        
        private string id_letter_userField;
        
        private string date_letter_userField;
        
        private string id_contactField;
        
        private string letter_textField;
        
        private Attachment[] attachmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string id_letter_obk {
            get {
                return this.id_letter_obkField;
            }
            set {
                this.id_letter_obkField = value;
                this.RaisePropertyChanged("id_letter_obk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string id_edo {
            get {
                return this.id_edoField;
            }
            set {
                this.id_edoField = value;
                this.RaisePropertyChanged("id_edo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string date_letter {
            get {
                return this.date_letterField;
            }
            set {
                this.date_letterField = value;
                this.RaisePropertyChanged("date_letter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string user_obk {
            get {
                return this.user_obkField;
            }
            set {
                this.user_obkField = value;
                this.RaisePropertyChanged("user_obk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string id_letter_user {
            get {
                return this.id_letter_userField;
            }
            set {
                this.id_letter_userField = value;
                this.RaisePropertyChanged("id_letter_user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string date_letter_user {
            get {
                return this.date_letter_userField;
            }
            set {
                this.date_letter_userField = value;
                this.RaisePropertyChanged("date_letter_user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string id_contact {
            get {
                return this.id_contactField;
            }
            set {
                this.id_contactField = value;
                this.RaisePropertyChanged("id_contact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string letter_text {
            get {
                return this.letter_textField;
            }
            set {
                this.letter_textField = value;
                this.RaisePropertyChanged("letter_text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public Attachment[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("attachments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:main.service.edo", ConfigurationName="ServiceWithEdo.Action")]
    public interface Action {
        
        // CODEGEN: Generating message contract since the operation sendINDocument is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sendINDocument", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PW.Ncels.ServiceWithEdo.EsedoException), Action="sendINDocument", Name="EsedoException", Namespace="urn:utilit.service.esedo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PW.Ncels.ServiceWithEdo.sendINDocumentResponse sendINDocument(PW.Ncels.ServiceWithEdo.sendINDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sendINDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<PW.Ncels.ServiceWithEdo.sendINDocumentResponse> sendINDocumentAsync(PW.Ncels.ServiceWithEdo.sendINDocumentRequest request);
        
        // CODEGEN: Generating message contract since the operation sendProjectDocument is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sendProjectDocument", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PW.Ncels.ServiceWithEdo.EsedoException), Action="sendProjectDocument", Name="EsedoException", Namespace="urn:utilit.service.esedo")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PW.Ncels.ServiceWithEdo.sendProjectDocumentResponse sendProjectDocument(PW.Ncels.ServiceWithEdo.sendProjectDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sendProjectDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<PW.Ncels.ServiceWithEdo.sendProjectDocumentResponse> sendProjectDocumentAsync(PW.Ncels.ServiceWithEdo.sendProjectDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendINDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:main.service.edo", Order=0)]
        public PW.Ncels.ServiceWithEdo.InParameters parameters;
        
        public sendINDocumentRequest() {
        }
        
        public sendINDocumentRequest(PW.Ncels.ServiceWithEdo.InParameters parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendINDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:main.service.edo", Order=0)]
        public bool sendINDocumentReturn;
        
        public sendINDocumentResponse() {
        }
        
        public sendINDocumentResponse(bool sendINDocumentReturn) {
            this.sendINDocumentReturn = sendINDocumentReturn;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:project.service.edo")]
    public partial class ProjectParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_letter_obkField;
        
        private string authorField;
        
        private string date_letterField;
        
        private string letter_SubjectField;
        
        private string letter_textField;
        
        private Attachment[] attachmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string id_letter_obk {
            get {
                return this.id_letter_obkField;
            }
            set {
                this.id_letter_obkField = value;
                this.RaisePropertyChanged("id_letter_obk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("author");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string date_letter {
            get {
                return this.date_letterField;
            }
            set {
                this.date_letterField = value;
                this.RaisePropertyChanged("date_letter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string letter_Subject {
            get {
                return this.letter_SubjectField;
            }
            set {
                this.letter_SubjectField = value;
                this.RaisePropertyChanged("letter_Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string letter_text {
            get {
                return this.letter_textField;
            }
            set {
                this.letter_textField = value;
                this.RaisePropertyChanged("letter_text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public Attachment[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("attachments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendProjectDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:main.service.edo", Order=0)]
        public PW.Ncels.ServiceWithEdo.ProjectParameters parameters1;
        
        public sendProjectDocumentRequest() {
        }
        
        public sendProjectDocumentRequest(PW.Ncels.ServiceWithEdo.ProjectParameters parameters1) {
            this.parameters1 = parameters1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendProjectDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:main.service.edo", Order=0)]
        public bool sendProjectDocumentReturn;
        
        public sendProjectDocumentResponse() {
        }
        
        public sendProjectDocumentResponse(bool sendProjectDocumentReturn) {
            this.sendProjectDocumentReturn = sendProjectDocumentReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActionChannel : PW.Ncels.ServiceWithEdo.Action, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActionClient : System.ServiceModel.ClientBase<PW.Ncels.ServiceWithEdo.Action>, PW.Ncels.ServiceWithEdo.Action {
        
        public ActionClient() {
        }
        
        public ActionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PW.Ncels.ServiceWithEdo.sendINDocumentResponse PW.Ncels.ServiceWithEdo.Action.sendINDocument(PW.Ncels.ServiceWithEdo.sendINDocumentRequest request) {
            return base.Channel.sendINDocument(request);
        }
        
        public bool sendINDocument(PW.Ncels.ServiceWithEdo.InParameters parameters) {
            PW.Ncels.ServiceWithEdo.sendINDocumentRequest inValue = new PW.Ncels.ServiceWithEdo.sendINDocumentRequest();
            inValue.parameters = parameters;
            PW.Ncels.ServiceWithEdo.sendINDocumentResponse retVal = ((PW.Ncels.ServiceWithEdo.Action)(this)).sendINDocument(inValue);
            return retVal.sendINDocumentReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PW.Ncels.ServiceWithEdo.sendINDocumentResponse> PW.Ncels.ServiceWithEdo.Action.sendINDocumentAsync(PW.Ncels.ServiceWithEdo.sendINDocumentRequest request) {
            return base.Channel.sendINDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PW.Ncels.ServiceWithEdo.sendINDocumentResponse> sendINDocumentAsync(PW.Ncels.ServiceWithEdo.InParameters parameters) {
            PW.Ncels.ServiceWithEdo.sendINDocumentRequest inValue = new PW.Ncels.ServiceWithEdo.sendINDocumentRequest();
            inValue.parameters = parameters;
            return ((PW.Ncels.ServiceWithEdo.Action)(this)).sendINDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PW.Ncels.ServiceWithEdo.sendProjectDocumentResponse PW.Ncels.ServiceWithEdo.Action.sendProjectDocument(PW.Ncels.ServiceWithEdo.sendProjectDocumentRequest request) {
            return base.Channel.sendProjectDocument(request);
        }
        
        public bool sendProjectDocument(PW.Ncels.ServiceWithEdo.ProjectParameters parameters1) {
            PW.Ncels.ServiceWithEdo.sendProjectDocumentRequest inValue = new PW.Ncels.ServiceWithEdo.sendProjectDocumentRequest();
            inValue.parameters1 = parameters1;
            PW.Ncels.ServiceWithEdo.sendProjectDocumentResponse retVal = ((PW.Ncels.ServiceWithEdo.Action)(this)).sendProjectDocument(inValue);
            return retVal.sendProjectDocumentReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PW.Ncels.ServiceWithEdo.sendProjectDocumentResponse> PW.Ncels.ServiceWithEdo.Action.sendProjectDocumentAsync(PW.Ncels.ServiceWithEdo.sendProjectDocumentRequest request) {
            return base.Channel.sendProjectDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PW.Ncels.ServiceWithEdo.sendProjectDocumentResponse> sendProjectDocumentAsync(PW.Ncels.ServiceWithEdo.ProjectParameters parameters1) {
            PW.Ncels.ServiceWithEdo.sendProjectDocumentRequest inValue = new PW.Ncels.ServiceWithEdo.sendProjectDocumentRequest();
            inValue.parameters1 = parameters1;
            return ((PW.Ncels.ServiceWithEdo.Action)(this)).sendProjectDocumentAsync(inValue);
        }
    }
}
