//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.Database.Recources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HistoryStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HistoryStr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PW.Ncels.Database.Recources.HistoryStr", typeof(HistoryStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вложение.
        /// </summary>
        public static string Attach {
            get {
                return ResourceManager.GetString("Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string Column_Document_Address {
            get {
                return ResourceManager.GetString("Column_Document_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид протокола.
        /// </summary>
        public static string Column_Document_AdministrativeTypeDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_AdministrativeTypeDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласователи.
        /// </summary>
        public static string Column_Document_AgreementsValue {
            get {
                return ResourceManager.GetString("Column_Document_AgreementsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответные документы.
        /// </summary>
        public static string Column_Document_AnswersValue {
            get {
                return ResourceManager.GetString("Column_Document_AnswersValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество вложений.
        /// </summary>
        public static string Column_Document_AppendixCount {
            get {
                return ResourceManager.GetString("Column_Document_AppendixCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес заявителя.
        /// </summary>
        public static string Column_Document_ApplicantAddress {
            get {
                return ResourceManager.GetString("Column_Document_ApplicantAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория заявителя.
        /// </summary>
        public static string Column_Document_ApplicantCategoryDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_ApplicantCategoryDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail заявителя.
        /// </summary>
        public static string Column_Document_ApplicantEmail {
            get {
                return ResourceManager.GetString("Column_Document_ApplicantEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ф.И.О. Заявителя.
        /// </summary>
        public static string Column_Document_ApplicantName {
            get {
                return ResourceManager.GetString("Column_Document_ApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон заявителя.
        /// </summary>
        public static string Column_Document_ApplicantPhone {
            get {
                return ResourceManager.GetString("Column_Document_ApplicantPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип заявителя.
        /// </summary>
        public static string Column_Document_ApplicantType {
            get {
                return ResourceManager.GetString("Column_Document_ApplicantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область/Штат.
        /// </summary>
        public static string Column_Document_Area {
            get {
                return ResourceManager.GetString("Column_Document_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вложение.
        /// </summary>
        public static string Column_Document_Attach {
            get {
                return ResourceManager.GetString("Column_Document_Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата ожидания ответа.
        /// </summary>
        public static string Column_Document_AwaitingResponseDate {
            get {
                return ResourceManager.GetString("Column_Document_AwaitingResponseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер бланка.
        /// </summary>
        public static string Column_Document_BlankNumber {
            get {
                return ResourceManager.GetString("Column_Document_BlankNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина обращения.
        /// </summary>
        public static string Column_Document_CauseCitizenDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_CauseCitizenDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория обращений.
        /// </summary>
        public static string Column_Document_CitizenCategoryDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_CitizenCategoryDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принятые меры.
        /// </summary>
        public static string Column_Document_CitizenResultDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_CitizenResultDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид обращения.
        /// </summary>
        public static string Column_Document_CitizenTypeDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_CitizenTypeDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string Column_Document_City {
            get {
                return ResourceManager.GetString("Column_Document_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополняет.
        /// </summary>
        public static string Column_Document_CompleteDocumentsValue {
            get {
                return ResourceManager.GetString("Column_Document_CompleteDocumentsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество копий.
        /// </summary>
        public static string Column_Document_CopiesCount {
            get {
                return ResourceManager.GetString("Column_Document_CopiesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о получателе.
        /// </summary>
        public static string Column_Document_CorrespondentsInfo {
            get {
                return ResourceManager.GetString("Column_Document_CorrespondentsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация.
        /// </summary>
        public static string Column_Document_CorrespondentsValue {
            get {
                return ResourceManager.GetString("Column_Document_CorrespondentsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество вложений/копий.
        /// </summary>
        public static string Column_Document_Counters {
            get {
                return ResourceManager.GetString("Column_Document_Counters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Область.
        /// </summary>
        public static string Column_Document_Country {
            get {
                return ResourceManager.GetString("Column_Document_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подразделение.
        /// </summary>
        public static string Column_Document_Department {
            get {
                return ResourceManager.GetString("Column_Document_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата документа.
        /// </summary>
        public static string Column_Document_DocumentDate {
            get {
                return ResourceManager.GetString("Column_Document_DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид документа.
        /// </summary>
        public static string Column_Document_DocumentDictionaryTypeValue {
            get {
                return ResourceManager.GetString("Column_Document_DocumentDictionaryTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип документа.
        /// </summary>
        public static string Column_Document_DocumentKindDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_DocumentKindDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменяет.
        /// </summary>
        public static string Column_Document_EditDocumentsValue {
            get {
                return ResourceManager.GetString("Column_Document_EditDocumentsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Column_Document_Email {
            get {
                return ResourceManager.GetString("Column_Document_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок исполнения.
        /// </summary>
        public static string Column_Document_ExecutionDate {
            get {
                return ResourceManager.GetString("Column_Document_ExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнители.
        /// </summary>
        public static string Column_Document_ExecutorsValue {
            get {
                return ResourceManager.GetString("Column_Document_ExecutorsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактическая дата исполнения.
        /// </summary>
        public static string Column_Document_FactExecutionDate {
            get {
                return ResourceManager.GetString("Column_Document_FactExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первичная дата исполнения.
        /// </summary>
        public static string Column_Document_FirstExecutionDate {
            get {
                return ResourceManager.GetString("Column_Document_FirstExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид доставки.
        /// </summary>
        public static string Column_Document_FormDeliveryDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_FormDeliveryDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид отправки.
        /// </summary>
        public static string Column_Document_FormSendingDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_FormSendingDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для служебного пользования.
        /// </summary>
        public static string Column_Document_IsAdministrativeUse {
            get {
                return ResourceManager.GetString("Column_Document_IsAdministrativeUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидает ответа.
        /// </summary>
        public static string Column_Document_IsAwaitingResponse {
            get {
                return ResourceManager.GetString("Column_Document_IsAwaitingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаленный.
        /// </summary>
        public static string Column_Document_IsDeleted {
            get {
                return ResourceManager.GetString("Column_Document_IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КТ.
        /// </summary>
        public static string Column_Document_IsTradeSecret {
            get {
                return ResourceManager.GetString("Column_Document_IsTradeSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КАТО.
        /// </summary>
        public static string Column_Document_KatoDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_KatoDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык документа.
        /// </summary>
        public static string Column_Document_LanguageDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_LanguageDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор контроля.
        /// </summary>
        public static string Column_Document_MonitoringAuthorValue {
            get {
                return ResourceManager.GetString("Column_Document_MonitoringAuthorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата контроля.
        /// </summary>
        public static string Column_Document_MonitoringDate {
            get {
                return ResourceManager.GetString("Column_Document_MonitoringDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примечание к контролю.
        /// </summary>
        public static string Column_Document_MonitoringNote {
            get {
                return ResourceManager.GetString("Column_Document_MonitoringNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип контроля.
        /// </summary>
        public static string Column_Document_MonitoringType {
            get {
                return ResourceManager.GetString("Column_Document_MonitoringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатура.
        /// </summary>
        public static string Column_Document_NomenclatureDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_NomenclatureDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примечание.
        /// </summary>
        public static string Column_Document_Note {
            get {
                return ResourceManager.GetString("Column_Document_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        public static string Column_Document_Number {
            get {
                return ResourceManager.GetString("Column_Document_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер бланка.
        /// </summary>
        public static string Column_Document_NumberBill {
            get {
                return ResourceManager.GetString("Column_Document_NumberBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата исходящего.
        /// </summary>
        public static string Column_Document_OutgoingDate {
            get {
                return ResourceManager.GetString("Column_Document_OutgoingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер исходящего.
        /// </summary>
        public static string Column_Document_OutgoingNumber {
            get {
                return ResourceManager.GetString("Column_Document_OutgoingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип исходящего.
        /// </summary>
        public static string Column_Document_OutgoingType {
            get {
                return ResourceManager.GetString("Column_Document_OutgoingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество листов.
        /// </summary>
        public static string Column_Document_PageCount {
            get {
                return ResourceManager.GetString("Column_Document_PageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Column_Document_Phone {
            get {
                return ResourceManager.GetString("Column_Document_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почтовый индекс.
        /// </summary>
        public static string Column_Document_Postcode {
            get {
                return ResourceManager.GetString("Column_Document_Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приоритет.
        /// </summary>
        public static string Column_Document_PriorityType {
            get {
                return ResourceManager.GetString("Column_Document_PriorityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата протокола.
        /// </summary>
        public static string Column_Document_ProtocolDate {
            get {
                return ResourceManager.GetString("Column_Document_ProtocolDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характер вопроса.
        /// </summary>
        public static string Column_Document_QuestionDesignDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_QuestionDesignDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для сведения.
        /// </summary>
        public static string Column_Document_ReadersValue {
            get {
                return ResourceManager.GetString("Column_Document_ReadersValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адресат.
        /// </summary>
        public static string Column_Document_RecipientsValue {
            get {
                return ResourceManager.GetString("Column_Document_RecipientsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистратор.
        /// </summary>
        public static string Column_Document_RegistratorValue {
            get {
                return ResourceManager.GetString("Column_Document_RegistratorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аннулирует.
        /// </summary>
        public static string Column_Document_RepealDocumentsValue {
            get {
                return ResourceManager.GetString("Column_Document_RepealDocumentsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резолюция.
        /// </summary>
        public static string Column_Document_ResolutionValue {
            get {
                return ResourceManager.GetString("Column_Document_ResolutionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответственный / Контроль за исполнением.
        /// </summary>
        public static string Column_Document_ResponsibleValue {
            get {
                return ResourceManager.GetString("Column_Document_ResponsibleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписавший.
        /// </summary>
        public static string Column_Document_SignerValue {
            get {
                return ResourceManager.GetString("Column_Document_SignerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма подписи.
        /// </summary>
        public static string Column_Document_SigningFormDictionaryValue {
            get {
                return ResourceManager.GetString("Column_Document_SigningFormDictionaryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус документа.
        /// </summary>
        public static string Column_Document_StateType {
            get {
                return ResourceManager.GetString("Column_Document_StateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое содержание.
        /// </summary>
        public static string Column_Document_Summary {
            get {
                return ResourceManager.GetString("Column_Document_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор задания.
        /// </summary>
        public static string Column_Task_AuthorValue {
            get {
                return ResourceManager.GetString("Column_Task_AuthorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задание на документ.
        /// </summary>
        public static string Column_Task_DocumentValue {
            get {
                return ResourceManager.GetString("Column_Task_DocumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Срок исполнения задания.
        /// </summary>
        public static string Column_Task_ExecutionDate {
            get {
                return ResourceManager.GetString("Column_Task_ExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель задания.
        /// </summary>
        public static string Column_Task_ExecutorValue {
            get {
                return ResourceManager.GetString("Column_Task_ExecutorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер задания.
        /// </summary>
        public static string Column_Task_Number {
            get {
                return ResourceManager.GetString("Column_Task_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус задания.
        /// </summary>
        public static string Column_Task_State {
            get {
                return ResourceManager.GetString("Column_Task_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст задания.
        /// </summary>
        public static string Column_Task_Text {
            get {
                return ResourceManager.GetString("Column_Task_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания срока действия.
        /// </summary>
        public static string Column_TMC_ExpiryDate {
            get {
                return ResourceManager.GetString("Column_TMC_ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выдачи.
        /// </summary>
        public static string Column_TMC_IssuedDate {
            get {
                return ResourceManager.GetString("Column_TMC_IssuedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата получения.
        /// </summary>
        public static string Column_TMC_ReceivingDate {
            get {
                return ResourceManager.GetString("Column_TMC_ReceivingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата перемещения.
        /// </summary>
        public static string Column_TMC_TransferDate {
            get {
                return ResourceManager.GetString("Column_TMC_TransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата использования.
        /// </summary>
        public static string Column_TMC_UsedDate {
            get {
                return ResourceManager.GetString("Column_TMC_UsedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание.
        /// </summary>
        public static string INSERT {
            get {
                return ResourceManager.GetString("INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Property_Комментарий {
            get {
                return ResourceManager.GetString("Property_Комментарий", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнение.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задание.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение.
        /// </summary>
        public static string UPDATE {
            get {
                return ResourceManager.GetString("UPDATE", resourceCulture);
            }
        }
    }
}
