//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.Ncels.LocalResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PW.Ncels.LocalResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активные.
        /// </summary>
        public static string ActivMenu {
            get {
                return ResourceManager.GetString("ActivMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОСЛЕРЕГИСТРАЦИОННЫЙ.
        /// </summary>
        public static string AfterRegistration {
            get {
                return ResourceManager.GetString("AfterRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string AllMenu {
            get {
                return ResourceManager.GetString("AllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка безопасности и качества ЛС, ИМН.
        /// </summary>
        public static string AssessSafetyLsImn {
            get {
                return ResourceManager.GetString("AssessSafetyLsImn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КАЛЬКУЛЯТОР ПО УСЛУГАМ.
        /// </summary>
        public static string CalculatorHelper {
            get {
                return ResourceManager.GetString("CalculatorHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Консультационные услуги.
        /// </summary>
        public static string ConsultingHelp {
            get {
                return ResourceManager.GetString("ConsultingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договор ИМН и МТ.
        /// </summary>
        public static string ContractImnMtMenu {
            get {
                return ResourceManager.GetString("ContractImnMtMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Договоры.
        /// </summary>
        public static string ContractMenu {
            get {
                return ResourceManager.GetString("ContractMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переписка.
        /// </summary>
        public static string ConversationMenu {
            get {
                return ResourceManager.GetString("ConversationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переписка ОБК.
        /// </summary>
        public static string ConversationObk {
            get {
                return ResourceManager.GetString("ConversationObk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string CreateAction {
            get {
                return ResourceManager.GetString("CreateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспертиза рекламных материалов.
        /// </summary>
        public static string ExpertizeAdvertItems {
            get {
                return ResourceManager.GetString("ExpertizeAdvertItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспертиза ЛС, ИМН и МТ.
        /// </summary>
        public static string ExpertizeLSIMNMT {
            get {
                return ResourceManager.GetString("ExpertizeLSIMNMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просроченные.
        /// </summary>
        public static string ExpiredMenu {
            get {
                return ResourceManager.GetString("ExpiredMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФАРМАЦИИ.
        /// </summary>
        public static string Farmacii {
            get {
                return ResourceManager.GetString("Farmacii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фармаконадзор.
        /// </summary>
        public static string Farmakonadzor {
            get {
                return ResourceManager.GetString("Farmakonadzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОБЩИЕ УСЛУГИ.
        /// </summary>
        public static string GeneralHelp {
            get {
                return ResourceManager.GetString("GeneralHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСРЕЕСТР.
        /// </summary>
        public static string GosReestr {
            get {
                return ResourceManager.GetString("GosReestr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домашняя страница.
        /// </summary>
        public static string HomePageMenu {
            get {
                return ResourceManager.GetString("HomePageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инструкция.
        /// </summary>
        public static string InstructionMenu {
            get {
                return ResourceManager.GetString("InstructionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАКОНОДАТЕЛЬСТВО.
        /// </summary>
        public static string LEGISLATION {
            get {
                return ResourceManager.GetString("LEGISLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список.
        /// </summary>
        public static string ListMenu {
            get {
                return ResourceManager.GetString("ListMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список внесений изменений цен на ИМН.
        /// </summary>
        public static string ListRedPriceForImn {
            get {
                return ResourceManager.GetString("ListRedPriceForImn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список внесений изменений цен на ЛС.
        /// </summary>
        public static string ListRedPriceForLCMenu {
            get {
                return ResourceManager.GetString("ListRedPriceForLCMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список регистраций цен на ИМН.
        /// </summary>
        public static string ListRegPriceForImnMenu {
            get {
                return ResourceManager.GetString("ListRegPriceForImnMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список регистраций цен на ЛС.
        /// </summary>
        public static string ListRegPriceForLcMenu {
            get {
                return ResourceManager.GetString("ListRegPriceForLcMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string LogOutMenu {
            get {
                return ResourceManager.GetString("LogOutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛС, ИМН и ТМ.
        /// </summary>
        public static string LsImnTm {
            get {
                return ResourceManager.GetString("LsImnTm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка условий производства ДИ, КИ, Фармаконадзор.
        /// </summary>
        public static string MarkFarmKondzor {
            get {
                return ResourceManager.GetString("MarkFarmKondzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЦЭЛС.
        /// </summary>
        public static string Ncels {
            get {
                return ResourceManager.GetString("Ncels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        public static string NotificationMenu {
            get {
                return ResourceManager.GetString("NotificationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОБК.
        /// </summary>
        public static string ObkMenu {
            get {
                return ResourceManager.GetString("ObkMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПЕРИОД ЛС, ИМН и МТ.
        /// </summary>
        public static string PeriodLsImnMt {
            get {
                return ResourceManager.GetString("PeriodLsImnMt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка проекта СРР.
        /// </summary>
        public static string PrepareProjectsSPP {
            get {
                return ResourceManager.GetString("PrepareProjectsSPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ценообразование.
        /// </summary>
        public static string PriceMenu {
            get {
                return ResourceManager.GetString("PriceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проведение биоэквивалентности.
        /// </summary>
        public static string ProcessOfBioEkvivalentost {
            get {
                return ResourceManager.GetString("ProcessOfBioEkvivalentost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр профиля.
        /// </summary>
        public static string ProfileLookMenu {
            get {
                return ResourceManager.GetString("ProfileLookMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекты договоров.
        /// </summary>
        public static string ProjectContractMenu {
            get {
                return ResourceManager.GetString("ProjectContractMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Референтное ценообразование.
        /// </summary>
        public static string ReferentPriceMenu {
            get {
                return ResourceManager.GetString("ReferentPriceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Референтное ценообразование ЛС, ИМН.
        /// </summary>
        public static string ReferentPriceMenuLsImn {
            get {
                return ResourceManager.GetString("ReferentPriceMenuLsImn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись на прием.
        /// </summary>
        public static string RegForDoctor {
            get {
                return ResourceManager.GetString("RegForDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация ЛС.
        /// </summary>
        public static string RegistrationLsMenu {
            get {
                return ResourceManager.GetString("RegistrationLsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegistrationMenu {
            get {
                return ResourceManager.GetString("RegistrationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки.
        /// </summary>
        public static string RequestMenu {
            get {
                return ResourceManager.GetString("RequestMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проведение ДИ.
        /// </summary>
        public static string TakingProcessDI {
            get {
                return ResourceManager.GetString("TakingProcessDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проведение КИ.
        /// </summary>
        public static string TakingprocessKI {
            get {
                return ResourceManager.GetString("TakingprocessKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод на государственный язык.
        /// </summary>
        public static string TranslateToNationalLanguage {
            get {
                return ResourceManager.GetString("TranslateToNationalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДОРЕГИСТРАЦИОННЫЙ.
        /// </summary>
        public static string UntilRegistration {
            get {
                return ResourceManager.GetString("UntilRegistration", resourceCulture);
            }
        }
    }
}
