ALTER TABLE OBK_MtPart ALTER COLUMN Model NVARCHAR(500) NULL 
ALTER TABLE OBK_MtPart ALTER COLUMN Specification NVARCHAR(500) NULL 
ALTER TABLE OBK_MtPart ALTER COLUMN ProducerName NVARCHAR(2000) NULL 
ALTER TABLE OBK_MtPart ALTER COLUMN CountryName NVARCHAR(500) NULL 