ALTER TABLE OBK_MtPart
ADD [Name] NVARCHAR(MAX) NULL,
  [NameKz] NVARCHAR(MAX) NULL
GO

UPDATE OBK_MtPart
SET [Name] = '',
  [Namekz] = ''
WHERE [Name] IS NULL
GO

ALTER TABLE OBK_MtPart
ALTER COLUMN [Name] NVARCHAR(MAX) NOT NULL
GO

ALTER TABLE OBK_MtPart
ALTER COLUMN [NameKz] NVARCHAR(MAX) NOT NULL
GO