USE [master]
GO
/****** Object:  Database [ncels]    Script Date: 09.03.2017 23:05:10 ******/
CREATE DATABASE [ncels]
 CONTAINMENT = NONE
GO
ALTER DATABASE [ncels] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ncels].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ncels] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ncels] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ncels] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ncels] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ncels] SET ARITHABORT OFF 
GO
ALTER DATABASE [ncels] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ncels] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ncels] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ncels] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ncels] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ncels] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ncels] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ncels] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ncels] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ncels] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ncels] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ncels] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ncels] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ncels] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO
ALTER DATABASE [ncels] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ncels] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ncels] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ncels] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ncels] SET  MULTI_USER 
GO
ALTER DATABASE [ncels] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ncels] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ncels] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ncels] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

/****** Object:  Table [dbo].[UpdateScripts]    Script Date: 07.03.2017 18:38:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

USE [ncels]
GO
CREATE TABLE [dbo].[UpdateScripts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[UpdatedAt] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO