import { Menu } from './menu.model';
export const verticalMenuItems = [
  new Menu (1, 'Заполнение данных', null, null, null, null, true, 0),
  new Menu (2, 'Подписание', '/ext/payment/signing', null, null, null, false, 0),
  new Menu (3, 'Сведение о стоимости', '/ext/payment/cost-info', null, null, null, false, 1),
  new Menu (4, 'Данные ИМН/МТ', '/ext/payment/data', null, null, null, false, 1),
  new Menu (5, 'Комплектация ИМН и МТ', '/ext/payment/equipment', null, null, null, false, 1),
  new Menu (6, 'Производитель ИМН и МТ и участок производства', '/ext/payment/manufacturer', null, null, null, false, 1),
  new Menu (7, 'Субект осуществляющии плату за произведение экспертизы', '/ext/payment/subject', null, null, null, false, 1),
  new Menu (8, 'Вложение', '/ext/payment/attachments', null, null, null, false, 1),
  // new Menu (15, 'Dynamic Menu', '/ext-payment-tab/dynamic-menu', null, 'list-ul', null, false, 0),
]
/*
export const verticalMenuItems = [
    new Menu (301, 'Сведение о стоимости', '/ext-payment-tab/cost-info', null, null, null, false, 0),
    new Menu (1, 'Dashboard', '/ext-payment-tab/dashboard', null, 'tachometer', null, false, 0),
    new Menu (2, 'Membership', '/ext-payment-tab/membership', null, 'users', null, false, 0),
    new Menu (3, 'UI Features', null, null, 'laptop', null, true, 0),
    new Menu (4, 'Buttons', '/ext-payment-tab/ui/buttons', null, 'keyboard-o', null, false, 3),
    new Menu (5, 'Cards', '/ext-payment-tab/ui/cards', null, 'address-card-o', null, false, 3),
    new Menu (6, 'Components', '/ext-payment-tab/ui/components', null, 'creative-commons', null, false, 3),
    new Menu (7, 'Icons', '/ext-payment-tab/ui/icons', null, 'font-awesome', null, false, 3),
    new Menu (8, 'List Group', '/ext-payment-tab/ui/list-group', null, 'th-list', null, false, 3),
    new Menu (9, 'Media Objects', '/ext-payment-tab/ui/media-objects', null, 'object-group', null, false, 3),
    new Menu (10, 'Tabs & Accordions', '/ext-payment-tab/ui/tabs-accordions', null, 'server', null, false, 3),
    new Menu (11, 'Typography', '/ext-payment-tab/ui/typography', null, 'font', null, false, 3),
    new Menu (15, 'Dynamic Menu', '/ext-payment-tab/dynamic-menu', null, 'list-ul', null, false, 0),
    new Menu (16, 'Mailbox', '/ext-payment-tab/mailbox', null, 'envelope-o', null, false, 0),
    new Menu (20, 'Form Elements', null, null, 'pencil-square-o', null, true, 0),
    new Menu (21, 'Form Controls', '/ext-payment-tab/form-elements/controls', null, 'check-square-o', null, false, 20),
    new Menu (22, 'Form Layouts', '/ext-payment-tab/form-elements/layouts', null, 'th-large', null, false, 20),
    new Menu (23, 'Form Validations', '/ext-payment-tab/form-elements/validations', null, 'exclamation-triangle', null, false, 20),
    new Menu (24, 'Form Wizard', '/ext-payment-tab/form-elements/wizard', null, 'magic', null, false, 20),
    new Menu (25, 'Editor', '/ext-payment-tab/form-elements/editor', null, 'pencil', null, false, 20),
    new Menu (26, 'Tables', null, null, 'table', null, true, 0),
    new Menu (27, 'Basic Tables', '/ext-payment-tab/tables/basic-tables', null, 'th', null, false, 26),
    new Menu (28, 'Dynamic Tables', null, null, 'th-large', null, true, 26),
    new Menu (29, 'Smart DataTable', '/ext-payment-tab/tables/dynamic-tables/smart', null, 'caret-right', null, false, 28),
    new Menu (30, 'NGX DataTable', '/ext-payment-tab/tables/dynamic-tables/ngx', null, 'caret-right', null, false, 28),
    new Menu (31, 'Tools', null, null, 'wrench', null, true, 0),
    new Menu (32, 'Drag & Drop', '/ext-payment-tab/tools/drag-drop', null, 'hand-paper-o', null, false, 31),
    new Menu (33, 'Resizable', '/ext-payment-tab/tools/resizable', null, 'expand', null, false, 31),
    new Menu (34, 'Toaster', '/ext-payment-tab/tools/toaster', null, 'bell-o', null, false, 31),
    new Menu (40, 'Pages', null, null, 'file-text-o', null, true, 0),
    new Menu (43, 'Login', '/login', null, 'sign-in', null, false, 40),
    new Menu (44, 'Register', '/register', null, 'registered', null, false, 40),
    new Menu (45, 'Blank', '/ext-payment-tab/blank', null, 'file-o', null, false, 40),
    new Menu (46, 'Error', '/pagenotfound', null, 'exclamation-circle', null, false, 40),
    new Menu (50, 'Calendar', '/ext-payment-tab/calendar', null, 'calendar', null, false, 0),
    new Menu (66, 'Maps', null, null, 'globe', null, true, 0),
    new Menu (67, 'Google Maps', '/ext-payment-tab/maps/googlemaps', null, 'map-marker', null, false, 66),
    new Menu (68, 'Leaflet Maps', '/ext-payment-tab/maps/leafletmaps', null, 'map-o', null, false, 66),
    new Menu (70, 'Charts', null, null, 'area-chart', null, true, 0),
    new Menu (71, 'Bar Charts', '/ext-payment-tab/charts/bar', null, 'bar-chart', null, false, 70),
    new Menu (72, 'Pie Charts', '/ext-payment-tab/charts/pie', null, 'pie-chart', null, false, 70),
    new Menu (73, 'Line Charts', '/ext-payment-tab/charts/line', null, 'line-chart', null, false, 70),
    new Menu (74, 'Bubble Charts', '/ext-payment-tab/charts/bubble', null, 'comment-o', null, false, 70),
    new Menu (140, 'Level 1', null, null, 'folder-open-o', null, true, 0),
    new Menu (141, 'Level 2', null, null, 'folder-open-o', null, true, 140),
    new Menu (142, 'Level 3', null, null, 'folder-open-o', null, true, 141),
    new Menu (143, 'Level 4', null, null, 'folder-open-o', null, true, 142),
    new Menu (144, 'Level 5', null, null, 'folder-o', null, false, 143),
    new Menu (200, 'External Link', null, 'http://themeseason.com', 'external-link', '_blank', false, 0)
]
*/
export const horizontalMenuItems = [
    new Menu (1, 'Dashboard', '/ext-payment-tab/dashboard', null, 'tachometer', null, false, 0),
    new Menu (2, 'Membership', '/ext-payment-tab/membership', null, 'users', null, false, 0),
    new Menu (3, 'UI Features', null, null, 'laptop', null, true, 0),
    new Menu (4, 'Buttons', '/ext-payment-tab/ui/buttons', null, 'keyboard-o', null, false, 3),
    new Menu (5, 'Cards', '/ext-payment-tab/ui/cards', null, 'address-card-o', null, false, 3),
    new Menu (6, 'Components', '/ext-payment-tab/ui/components', null, 'creative-commons', null, false, 3),
    new Menu (7, 'Icons', '/ext-payment-tab/ui/icons', null, 'font-awesome', null, false, 3),
    new Menu (8, 'List Group', '/ext-payment-tab/ui/list-group', null, 'th-list', null, false, 3),
    new Menu (9, 'Media Objects', '/ext-payment-tab/ui/media-objects', null, 'object-group', null, false, 3),
    new Menu (10, 'Tabs & Accordions', '/ext-payment-tab/ui/tabs-accordions', null, 'server', null, false, 3),
    new Menu (11, 'Typography', '/ext-payment-tab/ui/typography', null, 'font', null, false, 3),
    new Menu (31, 'Tools', null, null, 'wrench', null, true, 3),
    new Menu (32, 'Drag & Drop', '/ext-payment-tab/tools/drag-drop', null, 'hand-paper-o', null, false, 31),
    new Menu (33, 'Resizable', '/ext-payment-tab/tools/resizable', null, 'expand', null, false, 31),
    new Menu (34, 'Toaster', '/ext-payment-tab/tools/toaster', null, 'bell-o', null, false, 31),
    new Menu (20, 'Form Elements', null, null, 'pencil-square-o', null, true, 0),
    new Menu (21, 'Form Controls', '/ext-payment-tab/form-elements/controls', null, 'check-square-o', null, false, 20),
    new Menu (22, 'Form Layouts', '/ext-payment-tab/form-elements/layouts', null, 'th-large', null, false, 20),
    new Menu (23, 'Form Validations', '/ext-payment-tab/form-elements/validations', null, 'exclamation-triangle', null, false, 20),
    new Menu (24, 'Form Wizard', '/ext-payment-tab/form-elements/wizard', null, 'magic', null, false, 20),
    new Menu (25, 'Editor', '/ext-payment-tab/form-elements/editor', null, 'pencil', null, false, 20),
    new Menu (26, 'Tables', null, null, 'table', null, true, 20),
    new Menu (27, 'Basic Tables', '/ext-payment-tab/tables/basic-tables', null, 'th', null, false, 26),
    new Menu (28, 'Dynamic Tables', null, null, 'th-large', null, true, 26),
    new Menu (29, 'Smart DataTable', '/ext-payment-tab/tables/dynamic-tables/smart', null, 'caret-right', null, false, 28),
    new Menu (30, 'NGX DataTable', '/ext-payment-tab/tables/dynamic-tables/ngx', null, 'caret-right', null, false, 28),
    new Menu (40, 'Pages', null, null, 'file-text-o', null, true, 0),
    new Menu (15, 'Dynamic Menu', '/ext-payment-tab/dynamic-menu', null, 'list-ul', null, false, 40),
    new Menu (43, 'Login', '/login', null, 'sign-in', null, false, 40),
    new Menu (44, 'Register', '/register', null, 'registered', null, false, 40),
    new Menu (45, 'Blank', '/ext-payment-tab/blank', null, 'file-o', null, false, 40),
    new Menu (46, 'Error', '/pagenotfound', null, 'exclamation-circle', null, false, 40),
    new Menu (50, 'Calendar', '/ext-payment-tab/calendar', null, 'calendar', null, false, 40),
    new Menu (16, 'Mailbox', '/ext-payment-tab/mailbox', null, 'envelope-o', null, false, 40),
    new Menu (200, 'External Link', null, 'http://themeseason.com', 'external-link', '_blank', false, 40),
    new Menu (66, 'Maps', null, null, 'globe', null, true, 0),
    new Menu (67, 'Google Maps', '/ext-payment-tab/maps/googlemaps', null, 'map-marker', null, false, 66),
    new Menu (68, 'Leaflet Maps', '/ext-payment-tab/maps/leafletmaps', null, 'map-o', null, false, 66),
    new Menu (70, 'Charts', null, null, 'area-chart', null, true, 0),
    new Menu (71, 'Bar Charts', '/ext-payment-tab/charts/bar', null, 'bar-chart', null, false, 70),
    new Menu (72, 'Pie Charts', '/ext-payment-tab/charts/pie', null, 'pie-chart', null, false, 70),
    new Menu (73, 'Line Charts', '/ext-payment-tab/charts/line', null, 'line-chart', null, false, 70),
    new Menu (74, 'Bubble Charts', '/ext-payment-tab/charts/bubble', null, 'comment-o', null, false, 70)
]
